# Build settings
theme: type-on-strap
# remote_theme: sylhare/Type-on-Strap

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-twitch

collections:
  updates:
    output: true

# Site Settings
author: ChaelCodes
twitter:
  username: ChaelCodes
  card: summary
social:
  name: ChaelCodes
  links:
    - https://twitch.tv/ChaelCodes
    - https://twitter.com/ChaelCodes
    - https://github.com/ChaelCodes

# Site Settings
title: ChaelCodes
tagline: Portoflio
description: >- # this means to ignore newlines until "baseurl:"
  Rachael wants to share the joy and beauty of programming through
  programming games and regular open-source streams on Twitch. She's
  been a professional dev since 2012, 3x Team Lead, and manages an
  open-source repo for playing games of Monster of the Week. Currently,
  she works as a Developer Relations Engineer for New Relic.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.chael.codes" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ChaelCodes
github_username:  ChaelCodes

# Theme Settings
# meta
favicon: assets/favicon.png

# Header and Footer
header_text: ChaelCodes
header_feature_image: /assets/img/bagelbanner.jpg
footer_text: Cuddle your else's, Track your Performance, and Docker isn't Magic. <3

# Blog
excerpt: truncate

# PAGINATION
paginate: 10
paginate_path: "blog/page:num"

# Atom/RSS Feed
feed:
  collections:
    - updates

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
