name: Lint Code

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
    - run: bundle install
    - name: Rubocop
      run: bundle exec rubocop
